REPOSITORY_KICS_ARGUMENTS: --exclude-paths dev --fail-on high
REPOSITORY_TRIVY_ARGUMENTS: --severity HIGH,CRITICAL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
PRE_COMMANDS:
  - command: "apk add openssl-dev openssl-libs-static cmake gcc g++"
    cwd: "root"
