app:
  log_level: info

kafka:
  brokers: localhost:9092
  security_protocol: plaintext
  ssl:
    ca_location: /app/cert/kafka_ca.pem
    certificate_location: /app/cert/app_cert.pem
    key_location: /app/cert/app_key.pem
    key_password:
  consumer_group: ops-to-med
  input_topic: test-fhir
  output_topic: test-output
  offset_reset: earliest

fhir:
  medication:
    profile: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication
    system: https://miracum.org/fhir/NamingSystem/identifier/P21SurrogateMedicationId
  medication_administration:
    profile: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration
    system: https://fhir.diz.uni-marburg.de/sid/medication-administration-id