app:
  log_level: info

kafka:
  brokers: localhost:9092
  security_protocol: plaintext
  ssl:
    ca_location: /app/cert/kafka_ca.pem
    certificate_location: /app/cert/app_cert.pem
    key_location: /app/cert/app_key.pem
    key_password:
  consumer_group: ops-med
  input_topic: test-fhir
  output_topic: test-output
  offset_reset: earliest

fhir:
  medication:
    profile: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication
    system: https://fhir.diz.uni-marburg.de/sid/medication-id
  medication_statement:
    profile: https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationStatement
    system: https://fhir.diz.uni-marburg.de/sid/medication-statement-id
