services:
  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_EXTERNAL://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_MESSAGE_MAX_BYTES: 5242880
      KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
      KAFKA_COMPRESSION_TYPE: gzip
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:19092 --list
      interval: 30s
      timeout: 10s
      retries: 3

  akhq:
    image: tchiotludo/akhq:0.25.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          ui-options:
            topic.show-all-consumer-groups: true
            topic-data.sort: NEWEST
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:19092"
    ports:
      - "9000:8080"
    depends_on:
      - kafka

  fhir-data-loader:
    image: confluentinc/cp-kafkacat:7.1.12
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "while true; do
        kafkacat -b kafka:19092 -K: -t test-fhir -P -l /data/person-data.ndjson &&
        kafkacat -b kafka:19092 -K: -t test-fhir -P -l /data/procedure-data.ndjson;
        sleep 10;
      done"
    volumes:
      - ./person-data.ndjson:/data/person-data.ndjson:ro
      - ./procedure-data.ndjson:/data/procedure-data.ndjson:ro
    depends_on:
      kafka:
        condition: service_healthy
